name = "request"
main = "_worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat_v2"]
workers_dev = true

routes = [
  
  { pattern = "ava.game.naver.com.request.benx.workers.dev", custom_domain = true },  
  { pattern = "collection.linefriends.com.request.benx.workers.dev", custom_domain = true },  
  { pattern = "support.zoom.us.request.benx.workers.dev", custom_domain = true },  
  
  ]

[unsafe.metadata.observability]
enabled = true

[observability.logs]
enabled = true
